services:
  api:
    build: .
    container_name: nodues_api
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
