name: Switch to Render

on:
  schedule:
    - cron: '42 12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  switch-to-render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update vercel.json to Render
        run: |
          date
          sed -i 's|.*destination.*api/:path.*|      "destination": "https://nodues-jbzp.onrender.com/api/:path*"|' client/vercel.json
          cat client/vercel.json

      - name: Commit and Push
        run: |
          git config --global user.name "Deployment automation"
          git config --global user.email "bot@nodues.com"
          git add client/vercel.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Night Mode: Switched server to Render"
            git push origin main || (git pull --rebase origin main && git push origin main)
          fi
